targetInstance: ${TEST_URL:https://rd-professional-api-pr-525.service.core-compute-preview.internal}
s2s-url: ${S2S_URL_FOR_TESTS:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}

s2s-name: rd_professional_api

idam.api.url: ${IDAM_URL:https://idam-api.aat.platform.hmcts.net}
generated.user.email.pattern: ${GENERATED_USER_EMAIL_PATTERN:freg-test-user-%s@feemail.com}
test.user.password: ${TEST_USER_PASSWORD:Hmcts123}
oauth2.client.id: ${OAUTH2_CLIENT_ID:rd-professional-api}
oauth2.client.secret: ${OAUTH2_CLIENT_SECRET:cc5f2a6-9690-11e9-bc42-526af7764f64}
idam.auth.clientId: rd-professional-api

idam.auth.tokenAuth: ${IDAM_TOKEN_ATUH:cmQtcHJvZmVzc2lvbmFsLWFwaTpjYzVmMmE2LTk2OTAtMTFlOS1iYzQyLTUyNmFmNzc2NGY2NA==}
idam.auth.redirectUrl: ${OAUTH2_REDIRECT_URI:https://rd-professional-api-aat.service.core-compute-aat.internal/oauth2redirect}
s2s-secret: ${S2S_SECRET:K6KA6PRLRFWQLSD6}

spring.flyway.enabled: false
## Secure roles configuration 1
prd:
  security:
    roles:
      hmcts-admin: prd-admin
      pui-user-manager: pui-user-manager
      pui-organisation-manager: pui-organisation-manager
      pui-finance-manager: pui-finance-manager
      pui-case-manager: pui-case-manager
      pui-caa: pui-caa

# resent user invite interval in minutes
resendInterval: 60

# toggle for resendInvite
resendInviteEnabled : false