spring:
  flyway.locations: classpath:db/migration

  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:dbrefdata
    username: ${POSTGRES_USERNAME:dbrefdata}
    password: ${POSTGRES_PASSWORD:dbrefdata}


idam:
  s2s-authorised:
    services: rd_professional_api
  api.url: ${IDAM_URL:http://0.0.0.0:5000/o}
  client:
    redirect_uri: https://rd-professional-api-aat.service.core-compute-aat.internal/oauth2redirect
    id: rd-professional-api
    secret: cc5f2a6-9690-11e9-bc42-526af7764f64


## IDAM feign connection
auth.idam.client.baseUrl: ${http://0.0.0.0:5000/o}

exui.role:
  hmcts-admin: prd-admin
  pui-user-manager: pui-user-manager
  pui-organisation-manager: pui-organisation-manager
  pui-finance-manager: pui-finance-manager
  pui-case-manager: pui-case-manager

## user profile feign connection
user.profile.api.url: ${USER_PROFILE_URL:http://0.0.0.0:5000/o}
#oidc.issuer: ${OIDC_ISSUER:http://0.0.0.0:5000/openam/oauth2/hmcts}
## ccd jurisdiction feign connection
ccdUrl: ${CCD_URL:http://0.0.0.0:5000/o}

# resent user invite interval in minutes
resendInterval: 60

# sync time interval in minutes
syncInterval: 60