spring:
  flyway.locations: classpath:db/migration

  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  main:
    allow-bean-definition-overriding: true

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:dbrefdata
    username: ${POSTGRES_USERNAME:dbrefdata}
    password: ${POSTGRES_PASSWORD:dbrefdata}

auth.provider.service.client.baseUrl: ${S2S_URL:http://127.0.0.1:8990}
idam:
  s2s-authorised:
    services: ${PRD_S2S_AUTHORISED_SERVICES:rd_professional_api,rd_user_profile_api,xui_webapp,finrem_payment_service,fpl_case_service,iac}



## IDAM feign connection
auth.idam.client.baseUrl: ${IDAM_URL:http://127.0.0.1:5000}

exui.role:
  hmcts-admin: prd-admin
  pui-user-manager: pui-user-manager
  pui-organisation-manager: pui-organisation-manager
  pui-finance-manager: pui-finance-manager
  pui-case-manager: pui-case-manager

## user profile feign connection
user.profile.api.url: ${USER_PROFILE_URL:http://127.0.0.1:8091}

## ccd jurisdiction feign connection
ccdUrl: ${CCD_URL:http://127.0.0.1:8092}

# resent user invite interval in minutes
resendInterval: 60

# sync time interval in minutes
syncInterval: 60